services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8012:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

volumes:
  postgres_data:
